bt_navigator:
  ros__parameters:
    use_sim_time: true
    global_frame: odom
    robot_base_frame: base_link
    odom_topic: /odom
    transform_tolerance: 0.2
    default_bt_xml_filename: "$(find-pkg-share wheelchair_robot_description)bt_xml/local_nav.xml"

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 10.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001

    progress_checker_plugin: progress_checker
    goal_checker_plugin: goal_checker
    controller_plugins:
      - FollowPath

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0

    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.1
      yaw_goal_tolerance: 0.1
      stateful: false

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.3
      max_linear_accel: 0.5
      max_linear_decel: 0.5
      max_angular_vel: 1.0
      lookahead_dist: 0.6
      min_lookahead_dist: 0.3
      max_lookahead_dist: 0.9
      use_velocity_scaled_lookahead_dist: true
      transform_tolerance: 0.2
      use_rotate_to_heading: true
      allow_reversing: false
      rotate_to_heading_angular_vel: 0.5
      max_robot_pose_search_dist: 0.5

planner_server:
  ros__parameters:
    use_sim_time: true
    expected_planner_frequency: 5.0
    planner_plugins:
      - GridBased

    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"
      tolerance: 0.1
      use_astar: true
      allow_unknown: true

smoother_server:
  ros__parameters:
    use_sim_time: true
    smoother_plugins:
      - simple_smoother

    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0
      max_its: 1000
      do_refinement: true

behavior_server:
  ros__parameters:
    use_sim_time: true
    global_frame: odom
    robot_base_frame: base_link
    transform_tolerance: 0.2
    progress_checker_plugin: progress_checker
    goal_checker_plugin: goal_checker
    plugin_lib_names:
      - nav2_spin_behavior_server
      - nav2_back_up_behavior_server
      - nav2_wait_behavior_server
      - nav2_clear_costmap_service

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0

    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.1
      yaw_goal_tolerance: 0.1
      stateful: false

waypoint_follower:
  ros__parameters:
    use_sim_time: true
    loop_rate: 20
    stop_on_failure: true
    waypoint_task_executor_plugin: wait_at_waypoint

    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: true
      waypoint_pause_duration: 0

velocity_smoother:
  ros__parameters:
    use_sim_time: true
    smoothing_frequency: 20.0
    scale_velocities: true
    feedback: "OPEN_LOOP"
    max_velocity: [0.5, 0.0, 1.0]
    min_velocity: [-0.5, 0.0, -1.0]
    max_accel: [0.5, 0.0, 1.0]
    max_decel: [-0.5, 0.0, -1.0]
    odom_topic: "/odom"
    robot_base_frame: "base_link"

collision_monitor:
  ros__parameters:
    use_sim_time: true
    base_frame_id: base_link
    odom_frame_id: odom
    enabled: false
    polygons: ["PolygonStop"]
    PolygonStop:
      type: "polygon"
      points: "[[0.6, 0.3], [0.6, -0.3], [0.0, -0.3], [0.0, 0.3]]"
      action_type: "stop"
      min_points: 4
      visualize: True
      polygon_pub_topic: "/polygon_stop"
      enabled: True
    observation_sources: ["scan"]
    scan:
      type: "scan"
      topic: "/scan"
      enabled: True

route_server:
  ros__parameters:
    use_sim_time: true

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: odom
      robot_base_frame: base_link
      update_frequency: 10.0
      publish_frequency: 10.0
      transform_tolerance: 0.2
      rolling_window: true
      width: 6
      height: 6
      resolution: 0.05
      origin_x: 0.0
      origin_y: 0.0

      footprint: "[[0.5, 0.2], [0.5, -0.2], [-0.5, -0.2], [-0.5, 0.2]]"

      plugins:
        - obstacle_layer
        - inflation_layer

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 1.0
          clearing: true
          marking: true
          data_type: "LaserScan"
          raytrace_max_range: 5.0
          raytrace_min_range: 0.0
          obstacle_max_range: 4.0
          obstacle_min_range: 0.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.5
        cost_scaling_factor: 3.0

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: odom
      robot_base_frame: base_link
      update_frequency: 5.0
      publish_frequency: 5.0
      transform_tolerance: 0.2
      rolling_window: true
      width: 10
      height: 10
      resolution: 0.05
      origin_x: 0.0
      origin_y: 0.0

      footprint: "[[0.5, 0.2], [0.5, -0.2], [-0.5, -0.2], [-0.5, 0.2]]"

      plugins:
        - obstacle_layer
        - inflation_layer

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 1.0
          clearing: true
          marking: true
          data_type: "LaserScan"
          raytrace_max_range: 8.0
          raytrace_min_range: 0.0
          obstacle_max_range: 7.0
          obstacle_min_range: 0.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.7
        cost_scaling_factor: 3.0

